name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Les runners ont déjà le SDK; on accepte les licences et on installe ce qu'il faut.
      - name: Install Android SDK packages
        shell: bash
        run: |
          yes | sdkmanager --licenses >/dev/null
          sdkmanager "platform-tools" \
                     "platforms;android-34" \
                     "build-tools;34.0.0"

      # Installe Gradle 8.7 et active le cache
      - name: Setup Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Build Debug APK
        run: gradle --no-daemon clean :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sks-alibi-debug-apk
          path: app/build/outputs/apk/debug/*.apk
